---

- name: "PRELIM | Install and Start PostgreSQL | RHEL"
  block:
      - name: "PRELIM | Install and Start PostgreSQL | Add PostgreSQL Repo RHEL"
        ansible.builtin.package:
            name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm
            disable_gpg_check: "yes"
            state: present

      - name: "PRELIM | Install and Start PostgreSQL | Disable built in PostgreSQL RHEL"
        ansible.builtin.shell: dnf -y module disable postgresql
        register: prelim_disable_pgs
        changed_when: "'Disabling modules' in prelim_disable_pgs.stdout"

      - name: "PRELIM | Install and Start PostgreSQL | Install PostgreSQL 12 RHEL"
        ansible.builtin.package:
            name: ['postgresql12', 'postgresql12-server']
            state: present

      - name: "PRELIM | Install and Start PostgreSQL | Initialize PostgreSQL 12"
        ansible.builtin.shell: /usr/pgsql-12/bin/postgresql-12-setup initdb
        failed_when: false

      - name: "PRELIM | PRELIM | Install and Start PostgreSQL | Start and enable service"
        ansible.builtin.service:
            name: postgresql-12
            enabled: true
            state: started

      - name: "PRELIM | PRELIM | Install and Start PostgreSQL | Set postgres user pw"
        ansible.builtin.user:
            name: postgres
            password: "{{ pgs12cis_postgres_user_pw }}"
  when: ansible_distribution_file_variety == 'RedHat'

- name: "PRELIM | Install and Start PostgreSQL | Ubuntu"
  block:
      - name: "PRELIM | Install and Start PostgreSQL | Install wget for future task | Ubuntu"
        ansible.builtin.package:
            name: wget
            state: present

      - name: "PRELIM | Install and Start PostgreSQL | Get PostgreSQL GPG key | Ubuntu"
        ansible.builtin.shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

      - name: "PRELIM | Install and Start PostgreSQL | Add PostgreSQL repo | Ubuntu"
        ansible.builtin.shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list

      - name: "PRELIM | Install and Start PostgreSQL | Install PostgreSQL 12 | Ubuntu"
        ansible.builtin.package:
            name: ['postgresql-12', 'postgresql-client-12']
            state: present
            update_cache: true

      - name: "PRELIM | Install and Start PostgreSQL | Start and enable service | Ubuntu"
        ansible.builtin.service:
            name: postgresql
            state: started
            enabled: true

      - name: "PRELIM | PRELIM | Install and Start PostgreSQL | Set postgres user pw"
        ansible.builtin.user:
            name: postgres
            password: "{{ pgs12cis_postgres_user_pw }}"

  when: ansible_os_family == 'Debian'
