---

- name: "8.4 | AUDIT | Ensure miscellaneous configuration settings are correct"
  block:
      - name: "8.4 | AUDIT | Ensure miscellaneous configuration settings are correct | Get settings"
        ansible.builtin.shell: psql -c "select name, setting from pg_settings where name in ('external_pid_file', 'unix_socket_directories','shared_preload_libraries','dynamic_library_path',' local_preload_libraries','session_preload_libraries');"
        changed_when: false
        failed_when: false
        become_user: "{{ pgs12cis_pgs12_usr }}"
        register: pgs12cis_8_4_settings

      - name: "8.4 | AUDIT | Ensure miscellaneous configuration settings are correct | Display settings"
        ansible.builtin.debug:
            msg:
                - "Warning!! Please review the settings to confirm permissions are based on organization's policies. This is a manual task."
                - "{{ pgs12cis_8_4_settings.stdout_lines }}"

      - name: "8.4 | AUDIT | Ensure miscellaneous configuration settings are correct | Present"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '8.4'
  when:
      - pgs12cis_rule_8_4
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - audit
      - rhel
      - rule_8.4
