---

- name: "7.3 | AUDIT | Ensure base backups are configured and functional"
  ansible.builtin.debug:
      msg:
          - "Warning!! To conform to CIS standards make sure to use base backups. This is a manual task."

- name: "7.3 | AUDIT | Ensure base backups are configured and functional | Present"
  ansible.builtin.import_tasks:
      file: warning_facts.yml
  vars:
      warn_control_id: '7.3'
  when:
      - pgs12cis_rule_7_3
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - audit
      - rule_7.3
