---

- name: "7.3 | PATCH | Ensure WAL archiving is configured and functional"
  ansible.builtin.lineinfile:
      path: "{{ pgs12cis_config_file }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  notify: restart postgresql
  with_items:
      - { regexp: '^archive_mode =|^#archive_mode =', line: 'archive_mode = on' }
      - { regexp: '^archive_command =|^#archive_command =', line: "archive_command = '{{ pgs12cis_archive_command }}'" }
  when:
      - pgs12cis_rule_7_3
  tags:
      - level1-postgresqlonlinux
      - patch
      - rule_7.3
