---

- name: "7.5 | AUDIT | Ensure streaming replication parameters are configured correctly"
  ansible.builtin.debug:
      msg:
          - "Warning!! Please ensure streaming replication parameters are configured. This is a manual task."

- name: "7.5 | AUDIT | Ensure streaming replication parameters are configured correctly | Present"
  ansible.builtin.import_tasks:
      file: warning_facts.yml
  vars:
      warn_control_id: '7.5'
  when:
      - pgs12cis_rule_7_5
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - audit
      - rule_7.5
