---

- name: "6.4 | AUDIT | Ensure 'SIGHUP' Runtime Parameters are Configured"
  block:
      - name: "6.4 | AUDIT | Ensure 'SIGHUP' Runtime Parameters are Configured | Get sighup settings"
        ansible.builtin.shell: psql -c "SELECT name, setting FROM pg_settings WHERE context = 'sighup' ORDER BY 1;"
        changed_when: false
        failed_when: false
        become_user: "{{ pgs12cis_pgs12_usr }}"
        register: pgs12cis_6_4_sighup_settings

      - name: "6.4 | AUDIT | Ensure 'SIGHUP' Runtime Parameters are Configured | Message out settings"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below are the current sighup settings. Please revert all values in the PostgreSQL configuration files"
                - "and invoke the server to reload the configuration files. This is a manual task."
                - "{{ pgs12cis_6_4_sighup_settings.stdout_lines }}"

      - name: "6.4 | AUDIT | Ensure 'SIGHUP' Runtime Parameters are Configured | Present"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '6.4'
  when:
      - pgs12cis_rule_6_4
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - audit
      - rule_6.4
