---

- name: "6.5 | AUDIT | Ensure 'Superuser' Runtime Parameters are Configured"
  block:
      - name: "6.5 | AUDIT | Ensure 'Superuser' Runtime Parameters are Configured | Get superuser settings"
        ansible.builtin.shell: psql -c "SELECT name, setting FROM pg_settings WHERE context = 'superuser' ORDER BY 1;"
        changed_when: false
        failed_when: false
        become_user: "{{ pgs12cis_pgs12_usr }}"
        register: pgs12cis_6_5_superuser_settings

      - name: "6.5 | AUDIT | Ensure 'Superuser' Runtime Parameters are Configured | Get process output"
        ansible.builtin.shell: ps aux | grep -E 'postgres' | grep -- '-[D]'
        changed_when: false
        failed_when: false
        register: pgs12cis_6_5_process_output

      - name: "6.5 | AUDIT | Ensure 'Superuser' Runtime Parameters are Configured | Message out settings"
        ansible.builtin.debug:
            msg:
                - "Warning!! Please review this output and compare with a previous OK output looking for any changes"
                - "Also review the postgresql.conf and postgresql.auto.conf and compare them with previously archived files looking for changes"
                - "{{ pgs12cis_6_5_superuser_settings.stdout_lines }}"
                - ""
                - "Please review the process output below and look for parameters that were used at server startup. This is a manual task."
                - "{{ pgs12cis_6_5_process_output.stdout_lines }}"

      - name: "6.5 | AUDIT | Ensure 'Superuser' Runtime Parameters are Configured | Present"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '6.5'
  when:
      - pgs12cis_rule_6_5
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - audit
      - rule_6.5
