---

# this control makes it so you can't get run commands in postgres user
- name: "2.2 | PATCH | Ensure the PostgreSQL pg_wheel group membership is correct"
  block:
      - name: "2.2 | PATCH | Ensure the PostgreSQL pg_wheel group membership is correct | Create pg_wheel group"
        ansible.builtin.group:
            name: pg_wheel
            state: present

      - name: "2.2 | PATCH | Ensure the PostgreSQL pg_wheel group membership is correct"
        ansible.builtin.user:
            name: "{{ pgs12cis_pgs12_usr }}"
            groups: pg_wheel
  when:
      - pgs12cis_rule_2_2
  tags:
      - level1-postgresqlonlinux
      - patch
      - rule_2.2
