---

- name: "1.4 | PATCH | Ensure systemd Service Files Are Enabled"
  ansible.builtin.service:
      name: "{{ pgs12cis_postgresql_service }}"
      enabled: true
  when:
      - pgs12cis_rule_1_4
  tags:
      - level1-postgresqlonlinux
      - patch
      - rule_1.4
